name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan setiap hari pada tengah malam UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg

      - name: Push to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
